
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: writing_app_development

test:
  <<: *default
  database: writing_app_test

production:
  <<: *default
  database: writing_app_production
  username: writing_app
  password: <%= ENV['WRITING_APP_DATABASE_PASSWORD'] %>
